### ISSUE TITLE
Can you remove the dependency on railtie for non-rails uses?

### ISSUE THREAD

**Issue by jimbogit** [scoutapp/scout_statsd_rack#1]
I noticed when using this with a Sinatra app, that users of this have to require rails/railtie because
scout_statsd_rack.rb requires "scout_statsd_rack/railtie".

I'm not sure if that require is needed.  It doesn't appear to be (at least for non-rails) and would be great to not unnecessarily have to pull in unnecessary gems to use this.

**Comment by itsderek23** [comment]
@jimbogit,

Good catch. We'll check this out.

**Comment by blurredbits** [comment]
Please see version 0.1.6 on https://rubygems.org for the latest fix.
